name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.11"

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.8.2"

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      run: poetry run pytest tests

    - name: Deploy to GitHub Pages
      run: poetry run mkdocs gh-deploy --force